src/dashboard/Elsa.Dashboard/Models/Notification.cs
namespace Elsa.Dashboard.Models
{
    public class Notification
    {
        public Notification()
        {
        }
        
        public Notification(string message, NotificationType type = NotificationType.Information)
        {
            Message = message;
            Type = type;
        }
        
        public string Message { get; set; }
        public NotificationType Type { get; set; }
    }
}

src/dashboard/Elsa.Dashboard/Models/NotificationType.cs
namespace Elsa.Dashboard.Models
{
    public enum NotificationType
    {
        Success,
        Information,
        Warning,
        Error
    }
}

src/dashboard/Elsa.Dashboard/Areas/Elsa/Controllers/WorkflowDefinitionController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Elsa.Dashboard.Areas.Elsa.ViewModels;
using Elsa.Dashboard.Extensions;
using Elsa.Dashboard.Models;
using Elsa.Dashboard.Options;
using Elsa.Dashboard.Services;
using Elsa.Extensions;
using Elsa.Models;
using Elsa.Persistence;
using Elsa.Serialization;
using Elsa.Serialization.Formatters;
using Elsa.Services;
using Elsa.WorkflowDesigner.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Elsa.Dashboard.Areas.Elsa.Controllers
{
    [Area("Elsa")]
    [Route("[area]/workflow-definition")]
    public class WorkflowDefinitionController : Controller
    {
        private readonly IWorkflowDefinitionStore workflowDefinitionStore;
        private readonly IWorkflowInstanceStore workflowInstanceStore;
        private readonly IWorkflowPublisher publisher;
        private readonly IWorkflowSerializer serializer;
        private readonly IOptions<ElsaDashboardOptions> options;
        private readonly INotifier notifier;

        public WorkflowDefinitionController(
            IWorkflowDefinitionStore workflowDefinitionStore,
            IWorkflowInstanceStore workflowInstanceStore,
            IWorkflowPublisher publisher,
            IWorkflowSerializer serializer,
            IOptions<ElsaDashboardOptions> options,
            INotifier notifier)
        {
            this.publisher = publisher;
            this.workflowDefinitionStore = workflowDefinitionStore;
            this.workflowInstanceStore = workflowInstanceStore;
            this.serializer = serializer;
            this.options = options;
            this.notifier = notifier;
        }

        [HttpGet]
        public async Task<ViewResult> Index(CancellationToken cancellationToken)
        {
            var workflows = await workflowDefinitionStore.ListAsync(
                VersionOptions.LatestOrPublished,
                cancellationToken
            );
            
            var workflowModels = new List<WorkflowDefinitionListItemModel>();

            foreach (var workflow in workflows)
            {
                var workflowModel = await CreateWorkflowDefinitionListItemModelAsync(workflow, cancellationToken);
                workflowModels.Add(workflowModel);
            }
            
            var groups = workflowModels.GroupBy(x => x.WorkflowDefinition.DefinitionId);
            var model = new WorkflowDefinitionListViewModel
            {
                WorkflowDefinitions = groups.ToList()
            };
            return View(model);
        }

        [HttpGet("create")]
        public ViewResult Create()
        {
            var workflowDefinition = publisher.New();

            var model = new WorkflowDefinitionEditModel
            {
                Name = workflowDefinition.Name,
                Json = serializer.Serialize(workflowDefinition, JsonTokenFormatter.FormatName),
                ActivityDefinitions = options.Value.ActivityDefinitions.ToArray(),
                IsSingleton = workflowDefinition.IsSingleton,
                IsDisabled = workflowDefinition.IsDisabled,
                Description = workflowDefinition.Description
            };

            return View(model);
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create(WorkflowDefinitionEditModel model, CancellationToken cancellationToken)
        {
            var workflow = new WorkflowDefinitionVersion();
            return await SaveAsync(model, workflow, cancellationToken);
        }

        [HttpGet("edit/{id}", Name ="EditWorkflowDefinition")]
        public async Task<IActionResult> Edit(string id, CancellationToken cancellationToken)
        {
            var workflowDefinition = await publisher.GetDraftAsync(id, cancellationToken);

            if (workflowDefinition == null)
                return NotFound();

            var workflowModel = new WorkflowModel
            {
                Activities = workflowDefinition.Activities.Select(x => new ActivityModel(x)).ToList(),
                Connections = workflowDefinition.Connections.Select(x => new ConnectionModel(x)).ToList()
            };

            var model = new WorkflowDefinitionEditModel
            {
                Id = workflowDefinition.DefinitionId,
                Name = workflowDefinition.Name,
                Json = serializer.Serialize(workflowModel, JsonTokenFormatter.FormatName),
                Description = workflowDefinition.Description,
                IsSingleton = workflowDefinition.IsSingleton,
                IsDisabled = workflowDefinition.IsDisabled,
                ActivityDefinitions = options.Value.ActivityDefinitions.ToArray(),
                WorkflowModel = workflowModel
            };

            return View(model);
        }

        [HttpPost("edit/{id}")]
        public async Task<IActionResult> Edit(
            string id,
            WorkflowDefinitionEditModel model,
            CancellationToken cancellationToken)
        {
            var workflow = await workflowDefinitionStore.GetByIdAsync(id, VersionOptions.Latest, cancellationToken);
            return await SaveAsync(model, workflow, cancellationToken);
        }

        [HttpPost("delete/{id}")]
        public async Task<IActionResult> Delete(string id, CancellationToken cancellationToken)
        {
            await workflowDefinitionStore.DeleteAsync(id, cancellationToken);
            notifier.Notify("Workflow successfully deleted.", NotificationType.Success);
            return RedirectToAction(nameof(Index));
        }
        
        private async Task<IActionResult> SaveAsync(
            WorkflowDefinitionEditModel model,
            WorkflowDefinitionVersion workflow,
            CancellationToken cancellationToken)
        {
            var postedWorkflow = serializer.Deserialize<WorkflowModel>(model.Json, JsonTokenFormatter.FormatName);

            workflow.Activities = postedWorkflow.Activities
                .Select(x => new ActivityDefinition(x.Id, x.Type, x.State, x.Left, x.Top))
                .ToList();

            workflow.Connections = postedWorkflow.Connections.Select(
                x => new ConnectionDefinition(x.SourceActivityId, x.DestinationActivityId, x.Outcome)).ToList();

            workflow.Description = model.Description;
            workflow.Name = model.Name;
            workflow.IsDisabled = model.IsDisabled;
            workflow.IsSingleton = model.IsSingleton;

            var publish = model.SubmitAction == "publish";

            if (publish)
            {
                workflow = await publisher.PublishAsync(workflow, cancellationToken);
                notifier.Notify("Workflow successfully published.", NotificationType.Success);
            }
            else
            {
                workflow = await publisher.SaveDraftAsync(workflow, cancellationToken);
                notifier.Notify("Workflow successfully saved as a draft.", NotificationType.Success);
            }
            
            return RedirectToRoute("EditWorkflowDefinition", new { id = workflow.DefinitionId });
        }

        private async Task<WorkflowDefinitionListItemModel> CreateWorkflowDefinitionListItemModelAsync(
            WorkflowDefinitionVersion workflowDefinition,
            CancellationToken cancellationToken)
        {
            var instances = await workflowInstanceStore
                .ListByDefinitionAsync(workflowDefinition.DefinitionId, cancellationToken)
                .ToListAsync();

            return new WorkflowDefinitionListItemModel
            {
                WorkflowDefinition = workflowDefinition,
                AbortedCount = instances.Count(x => x.Status == WorkflowStatus.Aborted),
                FaultedCount = instances.Count(x => x.Status == WorkflowStatus.Faulted),
                FinishedCount = instances.Count(x => x.Status == WorkflowStatus.Finished),
                ExecutingCount = instances.Count(x => x.Status == WorkflowStatus.Executing),
            };
        }
    }
}

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/CustomScripts.cshtml
@using Elsa.Dashboard.Options
@using Microsoft.Extensions.Options
@inject IOptions<ElsaDashboardOptions> Options;

@{
    var scripts = Options.Value.Scripts;
    
    if (scripts?.Any() == true)
    {
        foreach (var script in scripts)
        {
            <script type="text/javascript" src="@Url.Content(script)"></script>
        }
    }
}

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/Footer.cshtml
<!-- Footer -->
<footer class="footer">
    <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                &copy; 2019 <a href="https://github.com/sfmskywalker" class="font-weight-bold ml-1" target="_blank">sfmskywalker</a>
            </div>
        </div>
        <div class="col-xl-6">
            <ul class="nav nav-footer justify-content-center justify-content-xl-end">
                <li class="nav-item">
                    <a href="https://github.com/elsa-workflows/elsa-core" class="nav-link" target="_blank">GitHub</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link" target="_blank">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="https://github.com/elsa-workflows/elsa-core/blob/develop/LICENSE" class="nav-link" target="_blank">BSD 3-Clause License</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/Notifications.cshtml
@using Elsa.Dashboard.ActionFilters
@using Elsa.Dashboard.Extensions
@using Elsa.Dashboard.Models
@{
    var notifications = TempData.Get<IList<Notification>>(NotifierFilter.TempDataKey);
}

@if (notifications != null)
{
    <div class="container-fluid align-items-center">
        <div class="row">
            <div class="col">
                @foreach (var notification in notifications)
                {
                    string iconClass;
                    string alertClass;
                    switch (notification.Type)
                    {
                        case NotificationType.Error:
                            iconClass = "fas fa-exclamation-circle mr-1";
                            alertClass = "alert-error";
                            break;
                        case NotificationType.Information:
                            iconClass = "ni ni-bulb-61";
                            alertClass = "alert-info";
                            break;
                        case NotificationType.Warning:
                            iconClass = "fas fa-exclamation-triangle mr-1";
                            alertClass = "alert-warning";
                            break;
                        default:
                            iconClass = "fas fa-check-circle mr-1";
                            alertClass = "alert-success";
                            break;
                    }
                    <div class="alert @alertClass alert-dismissible fade show col-xl-8 offset-xl-2 col-lg-12 offset-lg-0 col-md-12 offset-md-0 col-sm-12 offset-sm-0" role="alert">
                        <span class="alert-inner--icon">
                            <i class="@iconClass"></i>
                        </span>
                        <span class="alert-inner--text">@notification.Message</span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
}

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/SideBar.cshtml
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" asp-area="Elsa" asp-controller="Home" asp-action="Index">
            <h1 class="logo">
                Elsa
            </h1>
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            @await Html.PartialAsync("UserMenuItems")
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a asp-area="Elsa" asp-controller="Home" asp-action="Index">
                            <h1 class="logo">
                                Elsa
                            </h1>
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class=" nav-link" asp-controller="Home" asp-action="Index">
                        <i class="ni ni-tv-2 text-primary"></i> Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " asp-controller="WorkflowDefinition" asp-action="Index">
                        <i class="fa fa-sitemap fa-rotate-270 text-blue"></i> Workflows
                    </a>
                </li>
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <!-- Heading -->
            <h6 class="navbar-heading text-muted">Documentation</h6>
            <!-- Navigation -->
            <ul class="navbar-nav mb-md-3">
                <li class="nav-item">
                    <a class="nav-link" href="https://elsa-workflows.github.io/elsa-core/" target="_blank">
                        <i class="ni ni-spaceship"></i> Getting started
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/TopBar.cshtml
<!-- Navbar -->
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <span class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block">@ViewBag.Title</span>
        
        @await Html.PartialAsync("UserMenu")
    </div>
</nav>

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/UserMenu.cshtml
<!-- User -->
<ul class="navbar-nav align-items-center d-none d-md-flex">
    @await Html.PartialAsync("UserMenuItems")
</ul>

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/UserMenuItems.cshtml
@{
    var userName = User.Identity.IsAuthenticated ? User.Identity.Name : "Anonymous";
    var email = User.Identity.IsAuthenticated ? User.Identity.Name : "anonymous@domain.com";
}

<li class="nav-item dropdown">
    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <div class="media align-items-center">
            <span class="avatar avatar-sm rounded-circle">
            </span>
            <div class="media-body ml-2 d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">@userName</span>
            </div>
        </div>
    </a>
    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
        <div class=" dropdown-header noti-title">
            <h6 class="text-overflow m-0">Welcome!</h6>
        </div>
        <a href="~/examples/profile.html" class="dropdown-item">
            <i class="ni ni-single-02"></i>
            <span>My profile</span>
        </a>
        <a href="~/examples/profile.html" class="dropdown-item">
            <i class="ni ni-settings-gear-65"></i>
            <span>Settings</span>
        </a>
        <a href="~/examples/profile.html" class="dropdown-item">
            <i class="ni ni-calendar-grid-58"></i>
            <span>Activity</span>
        </a>
        <a href="~/examples/profile.html" class="dropdown-item">
            <i class="ni ni-support-16"></i>
            <span>Support</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#!" class="dropdown-item">
            <i class="ni ni-user-run"></i>
            <span>Logout</span>
        </a>
    </div>
</li>

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/WorkflowDefinitionEditor.cshtml
@model WorkflowDefinitionEditModel
@{
    var formAction = Model.Id == null ? "Create" : "Edit";
}
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 id="editorCaption" class="mb-0">@Model.Name</h3>
                            <small id="editorDescription" class="text-muted">@Model.Description</small>
                        </div>
                        <div class="col text-right">
                            <a href="#!" class="btn btn-primary" onclick="addActivity()">Add Activity</a>
                            <a href="#!" class="btn btn-secondary" onclick="exportWorkflow()">Download</a>
                            <a href="#!" class="btn btn-secondary" onclick="importWorkflow()">Import</a>
                            <a href="#!" class="btn btn-secondary" data-toggle="modal" data-target="#workflow-properties-modal">
                                <i class="ni ni-settings-gear-65"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form asp-action="@formAction">
                        <input asp-for="Json" id="workflowData" type="hidden"/>
                        <input asp-for="Name" type="hidden" id="workflowName"/>
                        <input asp-for="Description" type="hidden" id="workflowDescription"/>
                        <input asp-for="IsDisabled" type="hidden" id="workflowIsDisabled"/>
                        <input asp-for="IsSingleton" type="hidden" id="workflowIsSingleton"/>
                        <vc:workflow-designer id="designerHost" activity-definitions="@Model.ActivityDefinitions" workflow="@Model.WorkflowModel" is-readonly="@false" />
                        <div class="text-center">
                            <button asp-for="SubmitAction" name="SubmitAction" type="submit" value="draft" class="btn btn-primary mt-4">Save Draft</button>
                            <button asp-for="SubmitAction" name="SubmitAction" type="submit" value="publish" class="btn btn-success mt-4">Publish</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @await Html.PartialAsync("Footer")
</div>

<div class="modal fade" id="workflow-properties-modal" tabindex="-1" role="dialog" aria-labelledby="workflow-properties-modal" aria-hidden="true">
    <div class="modal-dialog modal- modal-dialog-centered modal-lg" role="document">
        <div class="modal-content bg-secondary">

            <div class="modal-header bg-white">
                <h2 class="modal-title" id="modal-title-default">Workflow Properties</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form role="form" onsubmit="onWorkflowPropertiesSubmit(event)">
                <div class="modal-body p-0">

                    <div class="card bg-secondary border-0">
                        <div class="card-body">

                            <h6 class="heading-small text-muted mb-4">Name and Description</h6>
                            <div class="pl-lg-4">
                                <div class="form-group focused">
                                    <label asp-for="Name" class="form-control-label">Name</label>
                                    <input asp-for="Name" class="form-control form-control-alternative" type="text">
                                </div>
                                <div class="form-group">
                                    <label asp-for="Description">Description</label>
                                    <textarea asp-for="Description" rows="4" class="form-control form-control-alternative"></textarea>
                                </div>
                                <div class="form-group">
                                    <div class="custom-control custom-checkbox">
                                        <input asp-for="IsSingleton" class="custom-control-input" type="checkbox">
                                        <label asp-for="IsSingleton" class="custom-control-label">Singleton</label>
                                    </div>
                                    <small class="text-muted">Check to mark this workflow as being a <a href="https://elsa-workflows.github.io/elsa-core/" target="_blank">singleton</a></small>
                                </div>
                                <div class="form-group">
                                    <div class="custom-control custom-checkbox">
                                        <input asp-for="IsDisabled" class="custom-control-input" type="checkbox">
                                        <label asp-for="IsDisabled" class="custom-control-label">Disabled</label>
                                    </div>
                                    <small class="text-muted">Check to disable this workflow. Disabled workflows won't be triggered.</small>
                                </div>
                            </div>
                            <hr class="my-4">

                        </div>
                    </div>

                </div>
                <div class="modal-footer ">
                    <input type="submit" class="btn btn-primary" value="Update"/>
                    <button type="button" class="btn btn-link  ml-auto" data-dismiss="modal">Cancel</button>
                </div>
            </form>

        </div>
    </div>
</div>

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/Shared/_Layout.cshtml
<!--

=========================================================
* Argon Dashboard - v1.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        Elsa Dashboard
    </title>
    <!-- Favicon -->
    <link href="~/_content/Elsa.Dashboard/assets/img/brand/favicon.png" rel="icon" type="image/png">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="~/_content/Elsa.Dashboard/assets/js/plugins/nucleo/css/nucleo.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />
    <!-- CSS Files -->
    <link href="~/_content/Elsa.Dashboard/assets/css/argon-dashboard.css?v=1.1.0" rel="stylesheet"/>
    <link href="~/_content/Elsa.Dashboard/assets/css/elsa.css?v=1.1.0" rel="stylesheet"/>
    <script type="module" src="~/_content/Elsa.Dashboard/assets/js/plugins/elsa-workflows/elsa-workflow-designer/elsa-workflow-designer.esm.js"></script>
    <script nomodule="" src="~/_content/Elsa.Dashboard/assets/js/plugins/elsa-workflows/elsa-workflow-designer/elsa-workflow-designer.js"></script>
    @await RenderSectionAsync("HeadScripts", false)
</head>

<body>
@await Html.PartialAsync("SideBar")
<div class="main-content">
    @await Html.PartialAsync("TopBar")
    <!-- End Navbar -->
    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="background-size: cover; background-position: center top;">
        <!-- Mask -->
        <span class="mask bg-gradient-default opacity-8"></span>
        <!-- Header container -->

        @await Html.PartialAsync("Notifications")
        @await RenderSectionAsync("ContentHeader", false)
    </div>
    <!-- Page content -->
    @RenderBody()
</div>
<!--   Core   -->
<script src="~/_content/Elsa.Dashboard/assets/js/plugins/jquery/dist/jquery.min.js"></script>
<script src="~/_content/Elsa.Dashboard/assets/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
@await Html.PartialAsync("CustomScripts")
@await RenderSectionAsync("FootScripts", false)
</body>

</html>