src/dashboard/Elsa.Dashboard/Areas/Elsa/Controllers/WorkflowDefinitionController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Elsa.Dashboard.Areas.Elsa.ViewModels;
using Elsa.Dashboard.Extensions;
using Elsa.Dashboard.Models;
using Elsa.Dashboard.Options;
using Elsa.Dashboard.Services;
using Elsa.Extensions;
using Elsa.Models;
using Elsa.Persistence;
using Elsa.Serialization;
using Elsa.Serialization.Formatters;
using Elsa.Services;
using Elsa.WorkflowDesigner.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Elsa.Dashboard.Areas.Elsa.Controllers
{
    [Area("Elsa")]
    [Route("[area]/workflow-definition")]
    public class WorkflowDefinitionController : Controller
    {
        private readonly IWorkflowDefinitionStore workflowDefinitionStore;
        private readonly IWorkflowInstanceStore workflowInstanceStore;
        private readonly IWorkflowPublisher publisher;
        private readonly IWorkflowSerializer serializer;
        private readonly IOptions<ElsaDashboardOptions> options;
        private readonly INotifier notifier;

        public WorkflowDefinitionController(
            IWorkflowDefinitionStore workflowDefinitionStore,
            IWorkflowInstanceStore workflowInstanceStore,
            IWorkflowPublisher publisher,
            IWorkflowSerializer serializer,
            IOptions<ElsaDashboardOptions> options,
            INotifier notifier)
        {
            this.publisher = publisher;
            this.workflowDefinitionStore = workflowDefinitionStore;
            this.workflowInstanceStore = workflowInstanceStore;
            this.serializer = serializer;
            this.options = options;
            this.notifier = notifier;
        }

        [HttpGet]
        public async Task<ViewResult> Index(CancellationToken cancellationToken)
        {
            var workflows = await workflowDefinitionStore.ListAsync(
                VersionOptions.LatestOrPublished,
                cancellationToken
            );
            
            var workflowModels = new List<WorkflowDefinitionListItemModel>();

            foreach (var workflow in workflows)
            {
                var workflowModel = await CreateWorkflowDefinitionListItemModelAsync(workflow, cancellationToken);
                workflowModels.Add(workflowModel);
            }
            
            var groups = workflowModels.GroupBy(x => x.WorkflowDefinition.DefinitionId);
            var model = new WorkflowDefinitionListViewModel
            {
                WorkflowDefinitions = groups.ToList()
            };
            return View(model);
        }

        [HttpGet("create")]
        public ViewResult Create()
        {
            var workflowDefinition = publisher.New();

            var model = new WorkflowDefinitionEditModel
            {
                Name = workflowDefinition.Name,
                Json = serializer.Serialize(workflowDefinition, JsonTokenFormatter.FormatName),
                ActivityDefinitions = options.Value.ActivityDefinitions.ToArray(),
                IsSingleton = workflowDefinition.IsSingleton,
                IsDisabled = workflowDefinition.IsDisabled,
                Description = workflowDefinition.Description
            };

            return View(model);
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create(WorkflowDefinitionEditModel model, CancellationToken cancellationToken)
        {
            var workflow = new WorkflowDefinitionVersion();
            return await SaveAsync(model, workflow, cancellationToken);
        }

        [HttpGet("edit/{id}", Name ="EditWorkflowDefinition")]
        public async Task<IActionResult> Edit(string id, CancellationToken cancellationToken)
        {
            var workflowDefinition = await publisher.GetDraftAsync(id, cancellationToken);

            if (workflowDefinition == null)
                return NotFound();

            var workflowModel = new WorkflowModel
            {
                Activities = workflowDefinition.Activities.Select(x => new ActivityModel(x)).ToList(),
                Connections = workflowDefinition.Connections.Select(x => new ConnectionModel(x)).ToList()
            };

            var model = new WorkflowDefinitionEditModel
            {
                Id = workflowDefinition.DefinitionId,
                Name = workflowDefinition.Name,
                Json = serializer.Serialize(workflowModel, JsonTokenFormatter.FormatName),
                Description = workflowDefinition.Description,
                IsSingleton = workflowDefinition.IsSingleton,
                IsDisabled = workflowDefinition.IsDisabled,
                ActivityDefinitions = options.Value.ActivityDefinitions.ToArray(),
                WorkflowModel = workflowModel
            };

            return View(model);
        }

        [HttpPost("edit/{id}")]
        public async Task<IActionResult> Edit(
            string id,
            WorkflowDefinitionEditModel model,
            CancellationToken cancellationToken)
        {
            var workflow = await workflowDefinitionStore.GetByIdAsync(id, VersionOptions.Latest, cancellationToken);
            return await SaveAsync(model, workflow, cancellationToken);
        }

        [HttpPost("delete/{id}")]
        public async Task<IActionResult> Delete(string id, CancellationToken cancellationToken)
        {
            await workflowDefinitionStore.DeleteAsync(id, cancellationToken);
            notifier.Notify("Workflow successfully deleted.", NotificationType.Success);
            return RedirectToAction(nameof(Index));
        }
        
        private async Task<IActionResult> SaveAsync(
            WorkflowDefinitionEditModel model,
            WorkflowDefinitionVersion workflow,
            CancellationToken cancellationToken)
        {
            var postedWorkflow = serializer.Deserialize<WorkflowModel>(model.Json, JsonTokenFormatter.FormatName);

            workflow.Activities = postedWorkflow.Activities
                .Select(x => new ActivityDefinition(x.Id, x.Type, x.State, x.Left, x.Top))
                .ToList();

            workflow.Connections = postedWorkflow.Connections.Select(
                x => new ConnectionDefinition(x.SourceActivityId, x.DestinationActivityId, x.Outcome)).ToList();

            workflow.Description = model.Description;
            workflow.Name = model.Name;
            workflow.IsDisabled = model.IsDisabled;
            workflow.IsSingleton = model.IsSingleton;

            var publish = model.SubmitAction == "publish";

            if (publish)
            {
                workflow = await publisher.PublishAsync(workflow, cancellationToken);
                notifier.Notify("Workflow successfully published.", NotificationType.Success);
            }
            else
            {
                workflow = await publisher.SaveDraftAsync(workflow, cancellationToken);
                notifier.Notify("Workflow successfully saved as a draft.", NotificationType.Success);
            }
            
            return RedirectToRoute("EditWorkflowDefinition", new { id = workflow.DefinitionId });
        }

        private async Task<WorkflowDefinitionListItemModel> CreateWorkflowDefinitionListItemModelAsync(
            WorkflowDefinitionVersion workflowDefinition,
            CancellationToken cancellationToken)
        {
            var instances = await workflowInstanceStore
                .ListByDefinitionAsync(workflowDefinition.DefinitionId, cancellationToken)
                .ToListAsync();

            return new WorkflowDefinitionListItemModel
            {
                WorkflowDefinition = workflowDefinition,
                AbortedCount = instances.Count(x => x.Status == WorkflowStatus.Aborted),
                FaultedCount = instances.Count(x => x.Status == WorkflowStatus.Faulted),
                FinishedCount = instances.Count(x => x.Status == WorkflowStatus.Finished),
                ExecutingCount = instances.Count(x => x.Status == WorkflowStatus.Executing),
            };
        }
    }
}

src/dashboard/Elsa.Dashboard/Areas/Elsa/Controllers/WorkflowInstanceController.cs
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Elsa.Dashboard.Areas.Elsa.ViewModels;
using Elsa.Dashboard.Extensions;
using Elsa.Dashboard.Models;
using Elsa.Dashboard.Options;
using Elsa.Dashboard.Services;
using Elsa.Extensions;
using Elsa.Models;
using Elsa.Persistence;
using Elsa.WorkflowDesigner.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Elsa.Dashboard.Areas.Elsa.Controllers
{
    [Area("Elsa")]
    [Route("[area]/workflow-instance")]
    public class WorkflowInstanceController : Controller
    {
        private readonly IWorkflowInstanceStore workflowInstanceStore;
        private readonly IWorkflowDefinitionStore workflowDefinitionStore;
        private readonly IOptions<ElsaDashboardOptions> options;
        private readonly INotifier notifier;

        public WorkflowInstanceController(
            IWorkflowInstanceStore workflowInstanceStore,
            IWorkflowDefinitionStore workflowDefinitionStore,
            IOptions<ElsaDashboardOptions> options,
            INotifier notifier)
        {
            this.workflowInstanceStore = workflowInstanceStore;
            this.workflowDefinitionStore = workflowDefinitionStore;
            this.options = options;
            this.notifier = notifier;
        }

        [HttpGet]
        public async Task<IActionResult> Index(
            string definitionId,
            WorkflowStatus status,
            CancellationToken cancellationToken)
        {
            var definition = await workflowDefinitionStore.GetByIdAsync(
                definitionId,
                VersionOptions.Latest,
                cancellationToken
            );

            if (definition == null)
                return NotFound();

            var instances = await workflowInstanceStore
                .ListByStatusAsync(definitionId, status, cancellationToken)
                .ToListAsync();

            var model = new WorkflowInstanceListViewModel
            {
                WorkflowDefinition = definition,
                ReturnUrl = Url.Action("Index", new { definitionId, status }),
                WorkflowInstances = instances.Select(
                        x => new WorkflowInstanceListItemModel
                        {
                            WorkflowInstance = x
                        }
                    )
                    .ToList()
            };

            return View(model);
        }

        [HttpGet("details/{id}")]
        public async Task<IActionResult> Details(string id, string returnUrl, CancellationToken cancellationToken)
        {
            var instance = await workflowInstanceStore.GetByIdAsync(id, cancellationToken);

            if (instance == null)
                return NotFound();

            var definition = await workflowDefinitionStore.GetByIdAsync(
                instance.DefinitionId,
                VersionOptions.SpecificVersion(instance.Version),
                cancellationToken
            );

            var workflow = new WorkflowModel
            {
                Activities = definition.Activities.Select(x => CreateActivityModel(x, instance)).ToList(),
                Connections = definition.Connections.Select(x => new ConnectionModel(x)).ToList()
            };

            var model = new WorkflowInstanceDetailsModel(
                instance,
                definition,
                workflow,
                options.Value.ActivityDefinitions,
                returnUrl);

            return View(model);
        }

        [HttpPost("delete/{id}")]
        public async Task<IActionResult> Delete(string id, string returnUrl, CancellationToken cancellationToken)
        {
            var instance = await workflowInstanceStore.GetByIdAsync(id, cancellationToken);

            if (instance == null)
                return NotFound();

            await workflowInstanceStore.DeleteAsync(id, cancellationToken);
            notifier.Notify("Workflow instance successfully deleted.", NotificationType.Success);

            if (Url.IsLocalUrl(returnUrl))
                return Redirect(returnUrl);

            return RedirectToAction("Index", "WorkflowDefinition");
        }

        private ActivityModel CreateActivityModel(
            ActivityDefinition activityDefinition,
            WorkflowInstance workflowInstance)
        {
            var isBlocking = workflowInstance.BlockingActivities.Any(x => x.ActivityId == activityDefinition.Id);
            var logEntry = workflowInstance.ExecutionLog.OrderByDescending(x => x.Timestamp)
                .FirstOrDefault(x => x.ActivityId == activityDefinition.Id);
            var isExecuted = logEntry != null;
            var isFaulted = logEntry?.Faulted ?? false;
            var message = default(ActivityMessageModel);

            if (isFaulted)
                message = new ActivityMessageModel("Faulted", logEntry.Message);
            else if (isBlocking)
                message = new ActivityMessageModel(
                    "Blocking",
                    "This activity is blocking workflow execution until the appropriate event is triggered.");
            else if (isExecuted)
                message = new ActivityMessageModel("Executed", logEntry.Message);

            return new ActivityModel(activityDefinition, isBlocking, isExecuted, isFaulted, message);
        }
    }
}

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/WorkflowDefinition/Create.cshtml
@model WorkflowDefinitionEditModel
@{
    ViewBag.Title = "New Workflow";
}

@await Html.PartialAsync("WorkflowDefinitionEditor")

@section FootScripts{
    <script src="~/_content/Elsa.Dashboard/assets/js/workflow-editor.js"></script>
}

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/WorkflowDefinition/Edit.cshtml
@model WorkflowDefinitionEditModel
@{
    ViewBag.Title = Model.Name;
}

@await Html.PartialAsync("WorkflowDefinitionEditor")

@section FootScripts{
    <script src="~/_content/Elsa.Dashboard/assets/js/workflow-editor.js"></script>
}

src/dashboard/Elsa.Dashboard/Areas/Elsa/Views/WorkflowDefinition/Index.cshtml
@model WorkflowDefinitionListViewModel
@{
    ViewBag.Title = "Workflows";

    var deleteUrlTemplate = Url.Action("Delete", new { id = "id" }).Replace("id", "${id}");
}

@section FootScripts
{
    <script type="text/javascript">
        const form = document.querySelector('#listForm');
        
        function onDeleteClick(e, id){
            e.preventDefault();
            
            if(!confirm('Are you sure you want to delete this workflow?'))
                return;
            
            form.action = `@Html.Raw(deleteUrlTemplate)`;
            form.submit();
        }
    </script>
}

<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Workflow Definitions</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a asp-action="Create" class="btn btn-primary">Create Workflow</a>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <form id="listForm" method="post" class="table-wrapper">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Description</th>
                                <th scope="col">Instances</th>
                                <th scope="col">Latest Version</th>
                                <th scope="col">Published Version</th>
                                <th scope="col">Enabled</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var grouping in Model.WorkflowDefinitions)
                            {
                                var latest = grouping.First(x => x.WorkflowDefinition.IsLatest);
                                var published = grouping.FirstOrDefault(x => x.WorkflowDefinition.IsPublished);
                                var publishedVersion = published?.WorkflowDefinition.Version.ToString() ?? "-";
                                <tr>
                                    <th scope="row">
                                        <div class="media align-items-center">
                                            <div class="media-body">
                                                <a asp-action="Edit" asp-route-id="@latest.WorkflowDefinition.DefinitionId" class="mb-0 text-sm">@latest.WorkflowDefinition.Name</a>
                                            </div>
                                        </div>
                                    </th>
                                    <td>@latest.WorkflowDefinition.Description</td>
                                    <td>
                                        <ul class="list-unstyled">
                                            @if (latest.ExecutingCount > 0)
                                            {
                                                <li>
                                                    <span class="badge badge-dot mr-4">
                                                        <i class="bg-info"></i>
                                                        <a
                                                            asp-action="Index"
                                                            asp-controller="WorkflowInstance"
                                                            asp-route-definitionId="@latest.WorkflowDefinition.DefinitionId"
                                                            asp-route-status="Executing">
                                                            @($"{latest.ExecutingCount} Executing")
                                                        </a>
                                                    </span>
                                                </li>
                                            }
                                            @if (latest.FaultedCount > 0)
                                            {
                                                <li>
                                                    <span class="badge badge-dot mr-4">
                                                        <i class="bg-warning"></i>
                                                        <a
                                                            asp-action="Index"
                                                            asp-controller="WorkflowInstance"
                                                            asp-route-definitionId="@latest.WorkflowDefinition.DefinitionId"
                                                            asp-route-status="Faulted">
                                                            @($"{latest.FaultedCount} Faulted")
                                                        </a>
                                                    </span>
                                                </li>
                                            }
                                            @if (latest.FinishedCount > 0)
                                            {
                                                <li>
                                                    <span class="badge badge-dot mr-4">
                                                        <i class="bg-success"></i>
                                                        <a
                                                            asp-action="Index"
                                                            asp-controller="WorkflowInstance"
                                                            asp-route-definitionId="@latest.WorkflowDefinition.DefinitionId"
                                                            asp-route-status="Finished">
                                                            @($"{latest.FinishedCount} Finished")
                                                        </a>
                                                    </span>
                                                </li>
                                            }
                                            @if (latest.AbortedCount > 0)
                                            {
                                                <li>
                                                    <span class="badge badge-dot mr-4">
                                                        <i class="bg-default"></i>
                                                        <a
                                                            asp-action="Index"
                                                            asp-controller="WorkflowInstance"
                                                            asp-route-definitionId="@latest.WorkflowDefinition.DefinitionId"
                                                            asp-route-status="Aborted">
                                                            @($"{latest.AbortedCount} Aborted")
                                                        </a>
                                                    </span>
                                                </li>
                                            }
                                        </ul>
                                    </td>
                                    <td>
                                        @latest.WorkflowDefinition.Version
                                    </td>
                                    <td>
                                        @publishedVersion
                                    </td>
                                    <td>
                                        <label class="custom-toggle disabled">
                                            <input type="checkbox" @if(!latest.WorkflowDefinition.IsDisabled){<text>checked</text>} disabled="disabled">
                                            <span class="custom-toggle-slider rounded-circle"></span>
                                        </label>
                                    </td>
                                    <td class="text-right">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item" asp-action="Edit" asp-route-id="@latest.WorkflowDefinition.DefinitionId">Edit</a>
                                                <a class="dropdown-item" href="#">Publish Draft</a>
                                                <a class="dropdown-item" href="#">Unpublish</a>
                                                <a class="dropdown-item" href="#">History</a>
                                                <a class="dropdown-item" href="#" onclick="onDeleteClick(event, '@latest.WorkflowDefinition.DefinitionId')">Delete</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="card-footer py-4">
                    <nav aria-label="...">
                        <ul class="pagination justify-content-end mb-0">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">
                                    <i class="fas fa-angle-left"></i>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            <li class="page-item active">
                                <a class="page-link" href="#">1</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">3</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">
                                    <i class="fas fa-angle-right"></i>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    @await Html.PartialAsync("Footer")
</div>